# Generated by Django 4.0.2 on 2022-03-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nopeb', models.CharField(max_length=200)),
                ('tanggalpeb', models.DateField()),
                ('npwpeksportir', models.CharField(max_length=15)),
                ('eksportir', models.CharField(max_length=200)),
                ('penerima', models.CharField(max_length=200)),
                ('alamatpenerima', models.CharField(max_length=200)),
                ('negarapenerima', models.CharField(max_length=200)),
                ('npwpppjk', models.CharField(max_length=15)),
                ('ppjk', models.CharField(max_length=200)),
                ('carrier', models.CharField(max_length=200)),
                ('flight', models.CharField(max_length=200)),
                ('pelmuatkode', models.CharField(max_length=3)),
                ('pelbongkarkode', models.CharField(max_length=3)),
                ('kodevaluta', models.CharField(max_length=3)),
                ('devisa', models.DecimalField(decimal_places=2, max_digits=20)),
                ('jumlahbarang', models.DecimalField(decimal_places=2, max_digits=20)),
                ('netto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bruto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('noseri', models.CharField(max_length=200)),
                ('kodehs', models.CharField(max_length=8)),
                ('namabarang', models.CharField(max_length=200)),
                ('jumlahitem', models.DecimalField(decimal_places=2, max_digits=20)),
                ('jeniskemasan', models.DecimalField(decimal_places=2, max_digits=20)),
                ('nettoitem', models.DecimalField(decimal_places=2, max_digits=20)),
                ('brutoitem', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tglberangkat', models.DateField()),
                ('jumlahkoli', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tonase', models.DecimalField(decimal_places=2, max_digits=20)),
                ('devisaitem', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tarifbk', models.CharField(max_length=3)),
                ('bk', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
