# Generated by Django 4.0.2 on 2022-03-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekspor_exim', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Dataekspor',
        ),
    ]
