# Generated by Django 4.0 on 2022-03-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataImpor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomor_PIB', models.CharField(max_length=6)),
                ('Tgl_PIB', models.DateField()),
                ('Nm_Importir', models.CharField(max_length=50)),
            ],
        ),
    ]
